<script>
export const words = [
  { word: "apple", definition: "A round fruit with red or green skin and a whitish inside." },
  { word: "plane", definition: "A powered flying vehicle with fixed wings and a weight greater than that of the air it displaces." },
  { word: "grape", definition: "A small, round, purple or green fruit that grows in bunches." },
  { word: "cloud", definition: "A visible mass of condensed water vapor floating in the atmosphere." },
  { word: "knife", definition: "A tool with a blade used for cutting." },
  { word: "horse", definition: "A large domesticated mammal used for riding and carrying loads." },
  { word: "clock", definition: "A device for measuring and indicating time." },
  { word: "mouse", definition: "A small rodent that typically has a pointed snout and a long tail." },
  { word: "heart", definition: "The organ that pumps blood through the circulatory system in humans and other animals." },
  { word: "table", definition: "A piece of furniture with a flat top and one or more legs, providing a level surface for eating, working, or placing things." },
  { word: "train", definition: "A series of connected vehicles traveling on railways." },
  { word: "chair", definition: "A seat with a back, typically having four legs." },
  { word: "beach", definition: "A pebbly or sandy shore, especially by the ocean." },
  { word: "smile", definition: "A pleased, kind, or amused expression, typically with the corners of the mouth turned up." },
  { word: "light", definition: "The natural agent that stimulates sight and makes things visible." },
  { word: "flame", definition: "The visible, gaseous part of a fire." },
  { word: "stone", definition: "A small piece of rock." },
  { word: "water", definition: "A clear, colorless, odorless, and tasteless liquid, essential for most plant and animal life." },
  { word: "seven", definition: "The number 7." },
  { word: "earth", definition: "The planet on which we live; the world." },
  { word: "river", definition: "A large, natural stream of water flowing in a channel to the sea, a lake, or another such stream." },
  { word: "piano", definition: "A large keyboard musical instrument with a wooden case enclosing a soundboard and metal strings." },
  { word: "grass", definition: "Vegetation consisting of typically short plants with long, narrow leaves, growing wild or cultivated on lawns and pastures." },
  { word: "shirt", definition: "A garment for the upper body made of cotton or a similar fabric, with a collar and sleeves, and with buttons down the front." },
  { word: "bread", definition: "A common food made from flour, water, and usually yeast." },
  { word: "crown", definition: "A circular ornamental headdress worn by a monarch as a symbol of authority." },
  { word: "truck", definition: "A large, heavy motor vehicle used for transporting goods, materials, or troops." },
  { word: "candy", definition: "A sweet food made with sugar or other sweeteners, typically formed in small pieces." },
  { word: "clock", definition: "A device for measuring and indicating time, typically by means of hands moving on a dial." },
  { word: "peach", definition: "A round, juicy fruit with fuzzy yellowish-pink skin and a large stone inside." },
  { word: "house", definition: "A building for human habitation, especially one that is lived in by a family or small group of people." },
  { word: "smoke", definition: "The visible vapor and gases given off by a burning substance." },
  { word: "sheep", definition: "A domesticated ruminant animal with a thick woolly coat." },
  { word: "storm", definition: "A violent disturbance of the atmosphere with strong winds and usually rain, thunder, lightning, or snow." },
  { word: "globe", definition: "A spherical representation of the earth or the heavens." },
  { word: "truck", definition: "A large motor vehicle designed to transport cargo." },
  { word: "bread", definition: "A common food made from flour, water, and usually yeast or another leavening agent, mixed together and baked." },
  { word: "skirt", definition: "A garment fastened around the waist and hanging down around the legs, worn by women and girls." },
  { word: "bloom", definition: "A flower, especially one cultivated for its beauty." },
  { word: "sunset", definition: "The time in the evening when the sun disappears below the horizon." },
  { word: "ocean", definition: "A large body of salt water that covers most of the earth's surface." },
  { word: "valley", definition: "A low area of land between hills or mountains, typically with a river or stream flowing through it." },
  { word: "forest", definition: "A large area covered chiefly with trees and undergrowth." },
  { word: "bridge", definition: "A structure carrying a road, path, railway, etc., across a river, road, or other obstacle." },
  { word: "flower", definition: "The seed-bearing part of a plant, consisting of reproductive organs typically surrounded by a brightly colored corolla (petals) and a green calyx (sepals)." },
  { word: "desert", definition: "A barren area of landscape where little precipitation occurs and, consequently, living conditions are hostile for plant and animal life." },
  { word: "rabbit", definition: "A small burrowing mammal with long ears, long hind legs, and a short tail." },
  { word: "orange", definition: "A round juicy citrus fruit with a tough bright reddish-yellow rind." },
  { word: "eagle", definition: "A large bird of prey with a massive hooked bill and long broad wings, renowned for its keen sight and powerful soaring flight." },
  { word: "winter", definition: "The coldest season of the year, in the northern hemisphere from December to February and in the southern hemisphere from June to August." },
];

export const getRandomWord = () => {
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
}
</script>